Update description
rambler-digital-solutions/danger-spec_postfix pull request #4
Opened 2023-01-18 08:37 UTC by peresvetjke

2023-01-19 09:06 UTC, mikhailushka requested changes

2023-01-19 09:06 UTC, mikhailushka commented on Gemfile.lock
> -    danger-spec_postfix (0.0.5)
Действительно ли 51 версия должна быть?

2023-01-19 09:19 UTC, peresvetjke commented on Gemfile.lock
> -    danger-spec_postfix (0.0.5)
уупс ) поправил.

2023-01-20 08:48 UTC, mikhailushka commented
LGTM!

2023-01-20 08:48 UTC, merged